index_addr: index_addr.s
	gcc -c $@.s -m32
	# gcc $@.s -o $@.out -m32
	ld -m elf_i386 -o $@.out $@.o -e main

index_addr2: index_addr2.s
	gcc -c $@.s -m32
	# gcc $@.s -o $@.out -m32
	ld -m elf_i386 -o $@.out $@.o -e main

index_addr3: index_addr3.s
	gcc -c $@.s -m32
	# gcc $@.s -o $@.out -m32
	ld -m elf_i386 -o $@.out $@.o -e main

address: address.s
	gcc -c $@.s -m32
	# gcc $@.s -o $@.out -m32
	ld -m elf_i386 -o $@.out $@.o -e main

var: var.s
	gcc -c $@.s -m32
	# gcc $@.s -o $@.out -m32
	ld -m elf_i386 -o $@.out $@.o -e main
